src/chatapp/urls.py
from django.urls import re_path
from . import views


app_name = 'chatapp'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^join/$', views.join, name='join'),
    re_path(r'^room/(?P<room_name>[\w-]+)/$', views.room, name='room')
]

src/chatserver/urls.py
from django.contrib import admin
from django.urls import path, include
import chatapp.views


urlpatterns = [
    path('', chatapp.views.index),
    path('admin/', admin.site.urls),
    path('chatapp/', include('chatapp.urls'))
]

src/chatserver/websocket/urls.py
from django.urls import re_path
import chatapp.consumers


urlpatterns = [
    re_path(r'^room/(?P<room_name>[\w-]+)/consumer$', chatapp.consumers.ChatConsumer.as_asgi())
]

src/chatapp/models.py
from django.db import models

# Create your models here.

src/chatapp/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse


def index(request):
    return render(request, 'chatapp/index.html')


def join(request):
    try:
        room_name = request.POST['room-name']
    except KeyError:
        raise Http404()
    else:
        return HttpResponseRedirect(reverse('chatapp:room', args=(room_name,)))


def room(request, room_name):
    return render(request, 'chatapp/room.html', {
        'room_name': room_name
    })

src/chatapp/templates/chatapp/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Chat Lobby</title>
    </head>
    <body>
        <form action="{% url 'chatapp:join' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="room-name"/>
            <input type="submit" value="Join"/>
        </form>
    </body>
</html>

src/chatapp/templates/chatapp/room.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Chat Room - {{ room_name }}</title>
    </head>
    <body>
        <textarea id="log" cols="10" rows="10"></textarea><br/>
        <input id="message" type="text"/><br/>
        <input id="send" type="button" value="send"/>
    </body>
</html>
<script>
const roomName = "{{ room_name }}";
const webSocket = new WebSocket(`ws://${window.location.host}/room/${roomName}/consumer`);
webSocket.addEventListener('message', (event) => {
    document.getElementById('log').value += `${JSON.parse(event.data)['message']}\n`;
});
document.getElementById('send').addEventListener('click', (event) => {
    webSocket.send(JSON.stringify({
        'message': document.getElementById('message').value
    }));
});
</script>